sudo: required

language: java

services:
  - docker

before_script: 
  - cd $TRAVIS_BUILD_DIR
  - echo "<settings><profiles><profile>
        <id>it</id>
        <properties>
          <postgresPassword>changeMe</postgresPassword>
          <mlrLegacyPasswd>changeMe</mlrLegacyPasswd>
          <mlrLegacyDataPasswd>changeMe</mlrLegacyDataPasswd>
          <mlrLegacyUserPasswd>changeMe</mlrLegacyUserPasswd>
          <mlrLegacyDataUsername>mlr_legacy_data</mlrLegacyDataUsername>
          <mlrLegacyServicePwd>changeMe</mlrLegacyServicePwd>
        </properties>
        </profile></profiles></settings>"
        > ~/settings.xml

script:
  - mvn verify --settings ~/settings.xml