
mybatis:
  type-aliases-package: gov.usgs.wma.mlrlegacy
  type-handlers-package: gov.usgs.wma.mlrlegacy
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
  mapper-locations: "classpath:monitoringLocation.xml"

spring:
  datasource:
    url: "jdbc:postgresql://${mlrLegacyDbHost}:${mlrLegacyDbPort}/mlr_legacy"
    username: ${mlrLegacyDataUsername}
    password: ${mlrLegacyDataPassword}
    driver-class-name: org.postgresql.Driver

jwt:
  header: Authorization
#  text from example
#  secret: my-very-secret-key

#  From mbucknell
#  secret: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqIiwEvm6rBa/9DbBU5HqVriuPyW6oxdD7yn9vampqpWAGnFUncUfN8sns/nflxUgSnCet9x+F62EUjU226v0GOsBmz9rLQ0c1LMvNse2ZiZSVz+w7RLqz31BZAJenOx0h0Oq05bbIMl/Pe/kDUtB5jSb41fWgEye+kQBic+8jTQFJWpA+7kOKQwmF580S9KDdOl5eiKmvXQ++opeVEraf79c8EuDLQVWnJUcVxKB4leIjFsul2Q6HZfB8WvWW6f5yppy/7F9Fp1JoELT7QaOWjDr2XC3r36F+Jl21YQv9jCQ8MgTJanTa6lhEgKCpnbieKItMMocvsoa2eNq0cltTwIDAQAB

# From drsteini
#  secret: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl36tMz4Ft7dQ3uK+2GqXds2HkqNplUaO1jqPq74wZ1Qkme0CECQpWN84bpVLbIlWoHufR01Ylig9ctgOwV2zOfCQ/s6sX3jgZd/cLPMTrzNfX0Wf+sX1LIhP+lTXhCHp6eZN9lFSiaOyPlT/lCjYGKujSRguSflfEIVMZUAMgBzhdJntBFK/9owjyHHIe1ZFJfsTak1XA1PGcdz7AvlYKhv+QCWn1ynvrJ5eXvqWEr/Z6S9tI7V1zSCphV3B8tZgsnv0+Y6S1QmS3r2Phum8B5dh0O2naxS6f7rFN6r1NUKQ0YktDIAbUPV2Fm3h8Yf3DqrtZRc9jMFVO3zcEhnfsQIDAQAB

  secret: MIIDdzCCAl+gAwIBAgIEbz8N9zANBgkqhkiG9w0BAQsFADBsMRAwDgYDVQQGEwdVbmtub3duMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMRAwDgYDVQQKEwdVbmtub3duMRAwDgYDVQQLEwdVbmtub3duMRAwDgYDVQQDEwdVbmtub3duMB4XDTE3MDkyNzE2MTk1MloXDTE3MTIyNjE2MTk1MlowbDEQMA4GA1UEBhMHVW5rbm93bjEQMA4GA1UECBMHVW5rbm93bjEQMA4GA1UEBxMHVW5rbm93bjEQMA4GA1UEChMHVW5rbm93bjEQMA4GA1UECxMHVW5rbm93bjEQMA4GA1UEAxMHVW5rbm93bjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKq5p6LCxZAayCW3FAbNeVNJIxJQyZndADX/cr8HOQE79xY54MCtlodVR3PMubaQxVsjJrJdAiVCBs2k8O9GCw+cm1VmzNEdispM0AYnB4Xoi354mXOJ1WFAhEn/ZyQw+5an8gQSMmiKD/TLsERNawEBwkx30hyBe3qSf3zBB8XHFobXzwq+NQSkvGLnsLZZ7CCyStlAPkwaYP1ZMJS1JviCnl/tTJNqa6kbcgnpDmaZ/Tj2Tm7NtpqEmruLJWcgaSQvQbA4yRv+n5/8Rd3oTI594gAYNTd08W576wD0W43x/2I2sUZPvnaLcyIau3A73nKu72mDJ4ZK/AQxQ8Sug68CAwEAAaMhMB8wHQYDVR0OBBYEFJgp0xEPceWXzW93HhIig+/3jSrgMA0GCSqGSIb3DQEBCwUAA4IBAQBDKw9WtaJf0LvnAFrlEsNRjFIsq1jr3Skhg8ir1efdjZW/X/t1w42bH9GsWHsU0EM/EEUrekQC4Bn7pKX16sJdbrhFgcWujABrE8fWU3DEmAqWENI+XDLRIvN+KA30IS0TbYcCziHWYBPIWkeRClsuBpPnnHZKl4LxG25ujLvBW7VzrICZxIfueZhkyKy+YwmOC4YIBDKWn7fwbtJo5i+aaJOZh1AKcdy4Gn3IO8xqpTb9wwwhv7gAenx5YxGov3wqeZ1sSotjxIz/EBi0SKflrH5LBFZ4sBOTEib2PPngNSDzPyhPqmvCdB7y9+rdbpk1L8v9gd6NPI8qrrz11nZ4
